// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.5
// source: api/proto/liuren.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LiurenInfoService_GetKeTiInfo_FullMethodName            = "/liuren.LiurenInfoService/GetKeTiInfo"
	LiurenInfoService_GetShenShaInfo_FullMethodName         = "/liuren.LiurenInfoService/GetShenShaInfo"
	LiurenInfoService_GetLiuQinInfo_FullMethodName          = "/liuren.LiurenInfoService/GetLiuQinInfo"
	LiurenInfoService_GetTianJiangInfo_FullMethodName       = "/liuren.LiurenInfoService/GetTianJiangInfo"
	LiurenInfoService_GetMonthGeneralInfo_FullMethodName    = "/liuren.LiurenInfoService/GetMonthGeneralInfo"
	LiurenInfoService_QueryDivinationHistory_FullMethodName = "/liuren.LiurenInfoService/QueryDivinationHistory"
)

// LiurenInfoServiceClient is the client API for LiurenInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 大六壬信息調用服務
type LiurenInfoServiceClient interface {
	// 查詢課體信息
	GetKeTiInfo(ctx context.Context, in *GetKeTiInfoRequest, opts ...grpc.CallOption) (*GetKeTiInfoResponse, error)
	// 查詢神煞信息
	GetShenShaInfo(ctx context.Context, in *GetShenShaInfoRequest, opts ...grpc.CallOption) (*GetShenShaInfoResponse, error)
	// 查詢六親關係
	GetLiuQinInfo(ctx context.Context, in *GetLiuQinInfoRequest, opts ...grpc.CallOption) (*GetLiuQinInfoResponse, error)
	// 查詢十二天將
	GetTianJiangInfo(ctx context.Context, in *GetTianJiangInfoRequest, opts ...grpc.CallOption) (*GetTianJiangInfoResponse, error)
	// 查詢月將信息
	GetMonthGeneralInfo(ctx context.Context, in *GetMonthGeneralInfoRequest, opts ...grpc.CallOption) (*GetMonthGeneralInfoResponse, error)
	// 查詢歷史排盤記錄（如存儲系統可用）
	QueryDivinationHistory(ctx context.Context, in *QueryDivinationHistoryRequest, opts ...grpc.CallOption) (*QueryDivinationHistoryResponse, error)
}

type liurenInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLiurenInfoServiceClient(cc grpc.ClientConnInterface) LiurenInfoServiceClient {
	return &liurenInfoServiceClient{cc}
}

func (c *liurenInfoServiceClient) GetKeTiInfo(ctx context.Context, in *GetKeTiInfoRequest, opts ...grpc.CallOption) (*GetKeTiInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeTiInfoResponse)
	err := c.cc.Invoke(ctx, LiurenInfoService_GetKeTiInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liurenInfoServiceClient) GetShenShaInfo(ctx context.Context, in *GetShenShaInfoRequest, opts ...grpc.CallOption) (*GetShenShaInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShenShaInfoResponse)
	err := c.cc.Invoke(ctx, LiurenInfoService_GetShenShaInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liurenInfoServiceClient) GetLiuQinInfo(ctx context.Context, in *GetLiuQinInfoRequest, opts ...grpc.CallOption) (*GetLiuQinInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLiuQinInfoResponse)
	err := c.cc.Invoke(ctx, LiurenInfoService_GetLiuQinInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liurenInfoServiceClient) GetTianJiangInfo(ctx context.Context, in *GetTianJiangInfoRequest, opts ...grpc.CallOption) (*GetTianJiangInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTianJiangInfoResponse)
	err := c.cc.Invoke(ctx, LiurenInfoService_GetTianJiangInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liurenInfoServiceClient) GetMonthGeneralInfo(ctx context.Context, in *GetMonthGeneralInfoRequest, opts ...grpc.CallOption) (*GetMonthGeneralInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthGeneralInfoResponse)
	err := c.cc.Invoke(ctx, LiurenInfoService_GetMonthGeneralInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liurenInfoServiceClient) QueryDivinationHistory(ctx context.Context, in *QueryDivinationHistoryRequest, opts ...grpc.CallOption) (*QueryDivinationHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryDivinationHistoryResponse)
	err := c.cc.Invoke(ctx, LiurenInfoService_QueryDivinationHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiurenInfoServiceServer is the server API for LiurenInfoService service.
// All implementations must embed UnimplementedLiurenInfoServiceServer
// for forward compatibility.
//
// 大六壬信息調用服務
type LiurenInfoServiceServer interface {
	// 查詢課體信息
	GetKeTiInfo(context.Context, *GetKeTiInfoRequest) (*GetKeTiInfoResponse, error)
	// 查詢神煞信息
	GetShenShaInfo(context.Context, *GetShenShaInfoRequest) (*GetShenShaInfoResponse, error)
	// 查詢六親關係
	GetLiuQinInfo(context.Context, *GetLiuQinInfoRequest) (*GetLiuQinInfoResponse, error)
	// 查詢十二天將
	GetTianJiangInfo(context.Context, *GetTianJiangInfoRequest) (*GetTianJiangInfoResponse, error)
	// 查詢月將信息
	GetMonthGeneralInfo(context.Context, *GetMonthGeneralInfoRequest) (*GetMonthGeneralInfoResponse, error)
	// 查詢歷史排盤記錄（如存儲系統可用）
	QueryDivinationHistory(context.Context, *QueryDivinationHistoryRequest) (*QueryDivinationHistoryResponse, error)
	mustEmbedUnimplementedLiurenInfoServiceServer()
}

// UnimplementedLiurenInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLiurenInfoServiceServer struct{}

func (UnimplementedLiurenInfoServiceServer) GetKeTiInfo(context.Context, *GetKeTiInfoRequest) (*GetKeTiInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeTiInfo not implemented")
}
func (UnimplementedLiurenInfoServiceServer) GetShenShaInfo(context.Context, *GetShenShaInfoRequest) (*GetShenShaInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShenShaInfo not implemented")
}
func (UnimplementedLiurenInfoServiceServer) GetLiuQinInfo(context.Context, *GetLiuQinInfoRequest) (*GetLiuQinInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLiuQinInfo not implemented")
}
func (UnimplementedLiurenInfoServiceServer) GetTianJiangInfo(context.Context, *GetTianJiangInfoRequest) (*GetTianJiangInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTianJiangInfo not implemented")
}
func (UnimplementedLiurenInfoServiceServer) GetMonthGeneralInfo(context.Context, *GetMonthGeneralInfoRequest) (*GetMonthGeneralInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthGeneralInfo not implemented")
}
func (UnimplementedLiurenInfoServiceServer) QueryDivinationHistory(context.Context, *QueryDivinationHistoryRequest) (*QueryDivinationHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryDivinationHistory not implemented")
}
func (UnimplementedLiurenInfoServiceServer) mustEmbedUnimplementedLiurenInfoServiceServer() {}
func (UnimplementedLiurenInfoServiceServer) testEmbeddedByValue()                           {}

// UnsafeLiurenInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiurenInfoServiceServer will
// result in compilation errors.
type UnsafeLiurenInfoServiceServer interface {
	mustEmbedUnimplementedLiurenInfoServiceServer()
}

func RegisterLiurenInfoServiceServer(s grpc.ServiceRegistrar, srv LiurenInfoServiceServer) {
	// If the following call panics, it indicates UnimplementedLiurenInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LiurenInfoService_ServiceDesc, srv)
}

func _LiurenInfoService_GetKeTiInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeTiInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiurenInfoServiceServer).GetKeTiInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiurenInfoService_GetKeTiInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiurenInfoServiceServer).GetKeTiInfo(ctx, req.(*GetKeTiInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiurenInfoService_GetShenShaInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShenShaInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiurenInfoServiceServer).GetShenShaInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiurenInfoService_GetShenShaInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiurenInfoServiceServer).GetShenShaInfo(ctx, req.(*GetShenShaInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiurenInfoService_GetLiuQinInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLiuQinInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiurenInfoServiceServer).GetLiuQinInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiurenInfoService_GetLiuQinInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiurenInfoServiceServer).GetLiuQinInfo(ctx, req.(*GetLiuQinInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiurenInfoService_GetTianJiangInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTianJiangInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiurenInfoServiceServer).GetTianJiangInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiurenInfoService_GetTianJiangInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiurenInfoServiceServer).GetTianJiangInfo(ctx, req.(*GetTianJiangInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiurenInfoService_GetMonthGeneralInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthGeneralInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiurenInfoServiceServer).GetMonthGeneralInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiurenInfoService_GetMonthGeneralInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiurenInfoServiceServer).GetMonthGeneralInfo(ctx, req.(*GetMonthGeneralInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiurenInfoService_QueryDivinationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDivinationHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiurenInfoServiceServer).QueryDivinationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiurenInfoService_QueryDivinationHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiurenInfoServiceServer).QueryDivinationHistory(ctx, req.(*QueryDivinationHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LiurenInfoService_ServiceDesc is the grpc.ServiceDesc for LiurenInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiurenInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "liuren.LiurenInfoService",
	HandlerType: (*LiurenInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKeTiInfo",
			Handler:    _LiurenInfoService_GetKeTiInfo_Handler,
		},
		{
			MethodName: "GetShenShaInfo",
			Handler:    _LiurenInfoService_GetShenShaInfo_Handler,
		},
		{
			MethodName: "GetLiuQinInfo",
			Handler:    _LiurenInfoService_GetLiuQinInfo_Handler,
		},
		{
			MethodName: "GetTianJiangInfo",
			Handler:    _LiurenInfoService_GetTianJiangInfo_Handler,
		},
		{
			MethodName: "GetMonthGeneralInfo",
			Handler:    _LiurenInfoService_GetMonthGeneralInfo_Handler,
		},
		{
			MethodName: "QueryDivinationHistory",
			Handler:    _LiurenInfoService_QueryDivinationHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/liuren.proto",
}
