// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/proto/liuren.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 課體信息請求
type GetKeTiInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeTiName      string                 `protobuf:"bytes,1,opt,name=ke_ti_name,json=keTiName,proto3" json:"ke_ti_name,omitempty"` // 課體名稱，為空則返回所有
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeTiInfoRequest) Reset() {
	*x = GetKeTiInfoRequest{}
	mi := &file_api_proto_liuren_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeTiInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeTiInfoRequest) ProtoMessage() {}

func (x *GetKeTiInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeTiInfoRequest.ProtoReflect.Descriptor instead.
func (*GetKeTiInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{0}
}

func (x *GetKeTiInfoRequest) GetKeTiName() string {
	if x != nil {
		return x.KeTiName
	}
	return ""
}

// 課體信息響應
type GetKeTiInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeTiList      []*KeTiInfo            `protobuf:"bytes,1,rep,name=ke_ti_list,json=keTiList,proto3" json:"ke_ti_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeTiInfoResponse) Reset() {
	*x = GetKeTiInfoResponse{}
	mi := &file_api_proto_liuren_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeTiInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeTiInfoResponse) ProtoMessage() {}

func (x *GetKeTiInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeTiInfoResponse.ProtoReflect.Descriptor instead.
func (*GetKeTiInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{1}
}

func (x *GetKeTiInfoResponse) GetKeTiList() []*KeTiInfo {
	if x != nil {
		return x.KeTiList
	}
	return nil
}

// 課體詳情
type KeTiInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Meaning       string                 `protobuf:"bytes,4,opt,name=meaning,proto3" json:"meaning,omitempty"`
	Features      []string               `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty"`
	Examples      []string               `protobuf:"bytes,6,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeTiInfo) Reset() {
	*x = KeTiInfo{}
	mi := &file_api_proto_liuren_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeTiInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeTiInfo) ProtoMessage() {}

func (x *KeTiInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeTiInfo.ProtoReflect.Descriptor instead.
func (*KeTiInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{2}
}

func (x *KeTiInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeTiInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *KeTiInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeTiInfo) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *KeTiInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *KeTiInfo) GetExamples() []string {
	if x != nil {
		return x.Examples
	}
	return nil
}

// 神煞信息請求
type GetShenShaInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShenShaName   string                 `protobuf:"bytes,1,opt,name=shen_sha_name,json=shenShaName,proto3" json:"shen_sha_name,omitempty"` // 神煞名稱，為空則返回所有
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShenShaInfoRequest) Reset() {
	*x = GetShenShaInfoRequest{}
	mi := &file_api_proto_liuren_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShenShaInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShenShaInfoRequest) ProtoMessage() {}

func (x *GetShenShaInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShenShaInfoRequest.ProtoReflect.Descriptor instead.
func (*GetShenShaInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{3}
}

func (x *GetShenShaInfoRequest) GetShenShaName() string {
	if x != nil {
		return x.ShenShaName
	}
	return ""
}

// 神煞信息響應
type GetShenShaInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShenShaList   []*ShenShaInfo         `protobuf:"bytes,1,rep,name=shen_sha_list,json=shenShaList,proto3" json:"shen_sha_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShenShaInfoResponse) Reset() {
	*x = GetShenShaInfoResponse{}
	mi := &file_api_proto_liuren_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShenShaInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShenShaInfoResponse) ProtoMessage() {}

func (x *GetShenShaInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShenShaInfoResponse.ProtoReflect.Descriptor instead.
func (*GetShenShaInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{4}
}

func (x *GetShenShaInfoResponse) GetShenShaList() []*ShenShaInfo {
	if x != nil {
		return x.ShenShaList
	}
	return nil
}

// 神煞詳情
type ShenShaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Meaning       string                 `protobuf:"bytes,3,opt,name=meaning,proto3" json:"meaning,omitempty"`
	Calculation   string                 `protobuf:"bytes,4,opt,name=calculation,proto3" json:"calculation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShenShaInfo) Reset() {
	*x = ShenShaInfo{}
	mi := &file_api_proto_liuren_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShenShaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShenShaInfo) ProtoMessage() {}

func (x *ShenShaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShenShaInfo.ProtoReflect.Descriptor instead.
func (*ShenShaInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{5}
}

func (x *ShenShaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShenShaInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShenShaInfo) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

func (x *ShenShaInfo) GetCalculation() string {
	if x != nil {
		return x.Calculation
	}
	return ""
}

// 六親信息請求
type GetLiuQinInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stem          string                 `protobuf:"bytes,1,opt,name=stem,proto3" json:"stem,omitempty"`     // 日干
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"` // 地支
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiuQinInfoRequest) Reset() {
	*x = GetLiuQinInfoRequest{}
	mi := &file_api_proto_liuren_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiuQinInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiuQinInfoRequest) ProtoMessage() {}

func (x *GetLiuQinInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiuQinInfoRequest.ProtoReflect.Descriptor instead.
func (*GetLiuQinInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{6}
}

func (x *GetLiuQinInfoRequest) GetStem() string {
	if x != nil {
		return x.Stem
	}
	return ""
}

func (x *GetLiuQinInfoRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

// 六親信息響應
type GetLiuQinInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relation      string                 `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"` // 六親關係名稱
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Meaning       string                 `protobuf:"bytes,3,opt,name=meaning,proto3" json:"meaning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiuQinInfoResponse) Reset() {
	*x = GetLiuQinInfoResponse{}
	mi := &file_api_proto_liuren_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiuQinInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiuQinInfoResponse) ProtoMessage() {}

func (x *GetLiuQinInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiuQinInfoResponse.ProtoReflect.Descriptor instead.
func (*GetLiuQinInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{7}
}

func (x *GetLiuQinInfoResponse) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GetLiuQinInfoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetLiuQinInfoResponse) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

// 天將信息請求
type GetTianJiangInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TianJiangName string                 `protobuf:"bytes,1,opt,name=tian_jiang_name,json=tianJiangName,proto3" json:"tian_jiang_name,omitempty"` // 天將名稱，為空則返回所有
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTianJiangInfoRequest) Reset() {
	*x = GetTianJiangInfoRequest{}
	mi := &file_api_proto_liuren_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTianJiangInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTianJiangInfoRequest) ProtoMessage() {}

func (x *GetTianJiangInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTianJiangInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTianJiangInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{8}
}

func (x *GetTianJiangInfoRequest) GetTianJiangName() string {
	if x != nil {
		return x.TianJiangName
	}
	return ""
}

// 天將信息響應
type GetTianJiangInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TianJiangList []*TianJiangInfo       `protobuf:"bytes,1,rep,name=tian_jiang_list,json=tianJiangList,proto3" json:"tian_jiang_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTianJiangInfoResponse) Reset() {
	*x = GetTianJiangInfoResponse{}
	mi := &file_api_proto_liuren_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTianJiangInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTianJiangInfoResponse) ProtoMessage() {}

func (x *GetTianJiangInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTianJiangInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTianJiangInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{9}
}

func (x *GetTianJiangInfoResponse) GetTianJiangList() []*TianJiangInfo {
	if x != nil {
		return x.TianJiangList
	}
	return nil
}

// 天將詳情
type TianJiangInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Nature        string                 `protobuf:"bytes,3,opt,name=nature,proto3" json:"nature,omitempty"` // 性質：吉/凶
	Meaning       string                 `protobuf:"bytes,4,opt,name=meaning,proto3" json:"meaning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TianJiangInfo) Reset() {
	*x = TianJiangInfo{}
	mi := &file_api_proto_liuren_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TianJiangInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TianJiangInfo) ProtoMessage() {}

func (x *TianJiangInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TianJiangInfo.ProtoReflect.Descriptor instead.
func (*TianJiangInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{10}
}

func (x *TianJiangInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TianJiangInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TianJiangInfo) GetNature() string {
	if x != nil {
		return x.Nature
	}
	return ""
}

func (x *TianJiangInfo) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

// 月將信息請求
type GetMonthGeneralInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // 月份名稱，為空則返回所有
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthGeneralInfoRequest) Reset() {
	*x = GetMonthGeneralInfoRequest{}
	mi := &file_api_proto_liuren_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthGeneralInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthGeneralInfoRequest) ProtoMessage() {}

func (x *GetMonthGeneralInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthGeneralInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMonthGeneralInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{11}
}

func (x *GetMonthGeneralInfoRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

// 月將信息響應
type GetMonthGeneralInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MonthGeneralList []*MonthGeneralInfo    `protobuf:"bytes,1,rep,name=month_general_list,json=monthGeneralList,proto3" json:"month_general_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMonthGeneralInfoResponse) Reset() {
	*x = GetMonthGeneralInfoResponse{}
	mi := &file_api_proto_liuren_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthGeneralInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthGeneralInfoResponse) ProtoMessage() {}

func (x *GetMonthGeneralInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthGeneralInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMonthGeneralInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{12}
}

func (x *GetMonthGeneralInfoResponse) GetMonthGeneralList() []*MonthGeneralInfo {
	if x != nil {
		return x.MonthGeneralList
	}
	return nil
}

// 月將詳情
type MonthGeneralInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Meaning       string                 `protobuf:"bytes,4,opt,name=meaning,proto3" json:"meaning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthGeneralInfo) Reset() {
	*x = MonthGeneralInfo{}
	mi := &file_api_proto_liuren_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthGeneralInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthGeneralInfo) ProtoMessage() {}

func (x *MonthGeneralInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthGeneralInfo.ProtoReflect.Descriptor instead.
func (*MonthGeneralInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{13}
}

func (x *MonthGeneralInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MonthGeneralInfo) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthGeneralInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MonthGeneralInfo) GetMeaning() string {
	if x != nil {
		return x.Meaning
	}
	return ""
}

// 歷史記錄查詢請求
type QueryDivinationHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // 限制數量
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDivinationHistoryRequest) Reset() {
	*x = QueryDivinationHistoryRequest{}
	mi := &file_api_proto_liuren_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDivinationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDivinationHistoryRequest) ProtoMessage() {}

func (x *QueryDivinationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDivinationHistoryRequest.ProtoReflect.Descriptor instead.
func (*QueryDivinationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{14}
}

func (x *QueryDivinationHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryDivinationHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// 歷史記錄查詢響應
type QueryDivinationHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*DivinationRecord    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDivinationHistoryResponse) Reset() {
	*x = QueryDivinationHistoryResponse{}
	mi := &file_api_proto_liuren_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDivinationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDivinationHistoryResponse) ProtoMessage() {}

func (x *QueryDivinationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDivinationHistoryResponse.ProtoReflect.Descriptor instead.
func (*QueryDivinationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{15}
}

func (x *QueryDivinationHistoryResponse) GetRecords() []*DivinationRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *QueryDivinationHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 排盤記錄
type DivinationRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Time          string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	YearPillar    string                 `protobuf:"bytes,4,opt,name=year_pillar,json=yearPillar,proto3" json:"year_pillar,omitempty"`
	MonthPillar   string                 `protobuf:"bytes,5,opt,name=month_pillar,json=monthPillar,proto3" json:"month_pillar,omitempty"`
	DayPillar     string                 `protobuf:"bytes,6,opt,name=day_pillar,json=dayPillar,proto3" json:"day_pillar,omitempty"`
	HourPillar    string                 `protobuf:"bytes,7,opt,name=hour_pillar,json=hourPillar,proto3" json:"hour_pillar,omitempty"`
	KeTi          string                 `protobuf:"bytes,8,opt,name=ke_ti,json=keTi,proto3" json:"ke_ti,omitempty"`
	XiongJi       string                 `protobuf:"bytes,9,opt,name=xiong_ji,json=xiongJi,proto3" json:"xiong_ji,omitempty"`
	Question      string                 `protobuf:"bytes,10,opt,name=question,proto3" json:"question,omitempty"`
	QuestionType  string                 `protobuf:"bytes,11,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DivinationRecord) Reset() {
	*x = DivinationRecord{}
	mi := &file_api_proto_liuren_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivinationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivinationRecord) ProtoMessage() {}

func (x *DivinationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_liuren_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivinationRecord.ProtoReflect.Descriptor instead.
func (*DivinationRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_liuren_proto_rawDescGZIP(), []int{16}
}

func (x *DivinationRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DivinationRecord) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DivinationRecord) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *DivinationRecord) GetYearPillar() string {
	if x != nil {
		return x.YearPillar
	}
	return ""
}

func (x *DivinationRecord) GetMonthPillar() string {
	if x != nil {
		return x.MonthPillar
	}
	return ""
}

func (x *DivinationRecord) GetDayPillar() string {
	if x != nil {
		return x.DayPillar
	}
	return ""
}

func (x *DivinationRecord) GetHourPillar() string {
	if x != nil {
		return x.HourPillar
	}
	return ""
}

func (x *DivinationRecord) GetKeTi() string {
	if x != nil {
		return x.KeTi
	}
	return ""
}

func (x *DivinationRecord) GetXiongJi() string {
	if x != nil {
		return x.XiongJi
	}
	return ""
}

func (x *DivinationRecord) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *DivinationRecord) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *DivinationRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_api_proto_liuren_proto protoreflect.FileDescriptor

const file_api_proto_liuren_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/liuren.proto\x12\x06liuren\"2\n" +
	"\x12GetKeTiInfoRequest\x12\x1c\n" +
	"\n" +
	"ke_ti_name\x18\x01 \x01(\tR\bkeTiName\"E\n" +
	"\x13GetKeTiInfoResponse\x12.\n" +
	"\n" +
	"ke_ti_list\x18\x01 \x03(\v2\x10.liuren.KeTiInfoR\bkeTiList\"\xae\x01\n" +
	"\bKeTiInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\ameaning\x18\x04 \x01(\tR\ameaning\x12\x1a\n" +
	"\bfeatures\x18\x05 \x03(\tR\bfeatures\x12\x1a\n" +
	"\bexamples\x18\x06 \x03(\tR\bexamples\";\n" +
	"\x15GetShenShaInfoRequest\x12\"\n" +
	"\rshen_sha_name\x18\x01 \x01(\tR\vshenShaName\"Q\n" +
	"\x16GetShenShaInfoResponse\x127\n" +
	"\rshen_sha_list\x18\x01 \x03(\v2\x13.liuren.ShenShaInfoR\vshenShaList\"\x7f\n" +
	"\vShenShaInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\ameaning\x18\x03 \x01(\tR\ameaning\x12 \n" +
	"\vcalculation\x18\x04 \x01(\tR\vcalculation\"B\n" +
	"\x14GetLiuQinInfoRequest\x12\x12\n" +
	"\x04stem\x18\x01 \x01(\tR\x04stem\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\"o\n" +
	"\x15GetLiuQinInfoResponse\x12\x1a\n" +
	"\brelation\x18\x01 \x01(\tR\brelation\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\ameaning\x18\x03 \x01(\tR\ameaning\"A\n" +
	"\x17GetTianJiangInfoRequest\x12&\n" +
	"\x0ftian_jiang_name\x18\x01 \x01(\tR\rtianJiangName\"Y\n" +
	"\x18GetTianJiangInfoResponse\x12=\n" +
	"\x0ftian_jiang_list\x18\x01 \x03(\v2\x15.liuren.TianJiangInfoR\rtianJiangList\"w\n" +
	"\rTianJiangInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06nature\x18\x03 \x01(\tR\x06nature\x12\x18\n" +
	"\ameaning\x18\x04 \x01(\tR\ameaning\"2\n" +
	"\x1aGetMonthGeneralInfoRequest\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\"e\n" +
	"\x1bGetMonthGeneralInfoResponse\x12F\n" +
	"\x12month_general_list\x18\x01 \x03(\v2\x18.liuren.MonthGeneralInfoR\x10monthGeneralList\"x\n" +
	"\x10MonthGeneralInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\ameaning\x18\x04 \x01(\tR\ameaning\"M\n" +
	"\x1dQueryDivinationHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"j\n" +
	"\x1eQueryDivinationHistoryResponse\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.liuren.DivinationRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xde\x02\n" +
	"\x10DivinationRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x1f\n" +
	"\vyear_pillar\x18\x04 \x01(\tR\n" +
	"yearPillar\x12!\n" +
	"\fmonth_pillar\x18\x05 \x01(\tR\vmonthPillar\x12\x1d\n" +
	"\n" +
	"day_pillar\x18\x06 \x01(\tR\tdayPillar\x12\x1f\n" +
	"\vhour_pillar\x18\a \x01(\tR\n" +
	"hourPillar\x12\x13\n" +
	"\x05ke_ti\x18\b \x01(\tR\x04keTi\x12\x19\n" +
	"\bxiong_ji\x18\t \x01(\tR\axiongJi\x12\x1a\n" +
	"\bquestion\x18\n" +
	" \x01(\tR\bquestion\x12#\n" +
	"\rquestion_type\x18\v \x01(\tR\fquestionType\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt2\x9a\x04\n" +
	"\x11LiurenInfoService\x12F\n" +
	"\vGetKeTiInfo\x12\x1a.liuren.GetKeTiInfoRequest\x1a\x1b.liuren.GetKeTiInfoResponse\x12O\n" +
	"\x0eGetShenShaInfo\x12\x1d.liuren.GetShenShaInfoRequest\x1a\x1e.liuren.GetShenShaInfoResponse\x12L\n" +
	"\rGetLiuQinInfo\x12\x1c.liuren.GetLiuQinInfoRequest\x1a\x1d.liuren.GetLiuQinInfoResponse\x12U\n" +
	"\x10GetTianJiangInfo\x12\x1f.liuren.GetTianJiangInfoRequest\x1a .liuren.GetTianJiangInfoResponse\x12^\n" +
	"\x13GetMonthGeneralInfo\x12\".liuren.GetMonthGeneralInfoRequest\x1a#.liuren.GetMonthGeneralInfoResponse\x12g\n" +
	"\x16QueryDivinationHistory\x12%.liuren.QueryDivinationHistoryRequest\x1a&.liuren.QueryDivinationHistoryResponseB-Z+github.com/kaecer68/liuren-zenith/api/protob\x06proto3"

var (
	file_api_proto_liuren_proto_rawDescOnce sync.Once
	file_api_proto_liuren_proto_rawDescData []byte
)

func file_api_proto_liuren_proto_rawDescGZIP() []byte {
	file_api_proto_liuren_proto_rawDescOnce.Do(func() {
		file_api_proto_liuren_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_liuren_proto_rawDesc), len(file_api_proto_liuren_proto_rawDesc)))
	})
	return file_api_proto_liuren_proto_rawDescData
}

var file_api_proto_liuren_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_liuren_proto_goTypes = []any{
	(*GetKeTiInfoRequest)(nil),             // 0: liuren.GetKeTiInfoRequest
	(*GetKeTiInfoResponse)(nil),            // 1: liuren.GetKeTiInfoResponse
	(*KeTiInfo)(nil),                       // 2: liuren.KeTiInfo
	(*GetShenShaInfoRequest)(nil),          // 3: liuren.GetShenShaInfoRequest
	(*GetShenShaInfoResponse)(nil),         // 4: liuren.GetShenShaInfoResponse
	(*ShenShaInfo)(nil),                    // 5: liuren.ShenShaInfo
	(*GetLiuQinInfoRequest)(nil),           // 6: liuren.GetLiuQinInfoRequest
	(*GetLiuQinInfoResponse)(nil),          // 7: liuren.GetLiuQinInfoResponse
	(*GetTianJiangInfoRequest)(nil),        // 8: liuren.GetTianJiangInfoRequest
	(*GetTianJiangInfoResponse)(nil),       // 9: liuren.GetTianJiangInfoResponse
	(*TianJiangInfo)(nil),                  // 10: liuren.TianJiangInfo
	(*GetMonthGeneralInfoRequest)(nil),     // 11: liuren.GetMonthGeneralInfoRequest
	(*GetMonthGeneralInfoResponse)(nil),    // 12: liuren.GetMonthGeneralInfoResponse
	(*MonthGeneralInfo)(nil),               // 13: liuren.MonthGeneralInfo
	(*QueryDivinationHistoryRequest)(nil),  // 14: liuren.QueryDivinationHistoryRequest
	(*QueryDivinationHistoryResponse)(nil), // 15: liuren.QueryDivinationHistoryResponse
	(*DivinationRecord)(nil),               // 16: liuren.DivinationRecord
}
var file_api_proto_liuren_proto_depIdxs = []int32{
	2,  // 0: liuren.GetKeTiInfoResponse.ke_ti_list:type_name -> liuren.KeTiInfo
	5,  // 1: liuren.GetShenShaInfoResponse.shen_sha_list:type_name -> liuren.ShenShaInfo
	10, // 2: liuren.GetTianJiangInfoResponse.tian_jiang_list:type_name -> liuren.TianJiangInfo
	13, // 3: liuren.GetMonthGeneralInfoResponse.month_general_list:type_name -> liuren.MonthGeneralInfo
	16, // 4: liuren.QueryDivinationHistoryResponse.records:type_name -> liuren.DivinationRecord
	0,  // 5: liuren.LiurenInfoService.GetKeTiInfo:input_type -> liuren.GetKeTiInfoRequest
	3,  // 6: liuren.LiurenInfoService.GetShenShaInfo:input_type -> liuren.GetShenShaInfoRequest
	6,  // 7: liuren.LiurenInfoService.GetLiuQinInfo:input_type -> liuren.GetLiuQinInfoRequest
	8,  // 8: liuren.LiurenInfoService.GetTianJiangInfo:input_type -> liuren.GetTianJiangInfoRequest
	11, // 9: liuren.LiurenInfoService.GetMonthGeneralInfo:input_type -> liuren.GetMonthGeneralInfoRequest
	14, // 10: liuren.LiurenInfoService.QueryDivinationHistory:input_type -> liuren.QueryDivinationHistoryRequest
	1,  // 11: liuren.LiurenInfoService.GetKeTiInfo:output_type -> liuren.GetKeTiInfoResponse
	4,  // 12: liuren.LiurenInfoService.GetShenShaInfo:output_type -> liuren.GetShenShaInfoResponse
	7,  // 13: liuren.LiurenInfoService.GetLiuQinInfo:output_type -> liuren.GetLiuQinInfoResponse
	9,  // 14: liuren.LiurenInfoService.GetTianJiangInfo:output_type -> liuren.GetTianJiangInfoResponse
	12, // 15: liuren.LiurenInfoService.GetMonthGeneralInfo:output_type -> liuren.GetMonthGeneralInfoResponse
	15, // 16: liuren.LiurenInfoService.QueryDivinationHistory:output_type -> liuren.QueryDivinationHistoryResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_liuren_proto_init() }
func file_api_proto_liuren_proto_init() {
	if File_api_proto_liuren_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_liuren_proto_rawDesc), len(file_api_proto_liuren_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_liuren_proto_goTypes,
		DependencyIndexes: file_api_proto_liuren_proto_depIdxs,
		MessageInfos:      file_api_proto_liuren_proto_msgTypes,
	}.Build()
	File_api_proto_liuren_proto = out.File
	file_api_proto_liuren_proto_goTypes = nil
	file_api_proto_liuren_proto_depIdxs = nil
}
